# Generated by Django 6.0.5 on 2026-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_manager', '0002_auto_20240515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushlog',
            options={'ordering': ['-created_at'], 'verbose_name': "Log d'action", 'verbose_name_plural': "Logs d'actions"},
        ),
        migrations.RenameIndex(
            model_name='pushlog',
            new_name='git_manager_created_1f443f_idx',
            old_name='git_manager_created_ idx',
        ),
        migrations.RenameIndex(
            model_name='pushlog',
            new_name='git_manager_status_07a351_idx',
            old_name='git_manager_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pushlog',
            new_name='git_manager_trigger_4c86de_idx',
            old_name='git_manager_trigger_idx',
        ),
        migrations.AddField(
            model_name='pushlog',
            name='action',
            field=models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('fetch', 'Fetch'), ('test', 'Test'), ('check', 'Vérification')], default='push', max_length=20),
        ),
        migrations.AlterField(
            model_name='gitremote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gitrepo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
