apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-git-manager-repos
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.24
    path: /share/container/git_repositories
