apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-git-manager-ssh
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.24
    path: /share/container/git-manager/ssh
