apiVersion: v1
kind: Service
metadata:
  name: git-manager-ssh
  namespace: git-manager
spec:
  selector:
    app: git-manager
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222
  type: NodePort
